name: dev

on: 
  push:
    branches:
      - dev
  workflow_dispatch: 
    inputs:
      terraform_action:
        type: choice
        description: Select terraform action
        default: plan
        options: 
          - apply
          - plan
jobs:
  Terraform_Apply_Plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
            terraform_version: 1.5.5

      - name: 'Az CLI Login'
        uses: azure/login@v1
        with: 
          creds: ${{ secrets.AZURE_CREDENTIALS}}
   
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Show terraform version
        run: |
          cd ${TF_PATH}
          terraform version
      - name: Terraform Init
        run: terraform init
      - name: Terraform Validate
        run: terraform validate
      - name: Terraform Plan
        id: tf-plan
        run: |
         export exitcode=0
          terraform plan -detailed-exitcode -no-color -out tfplan || export exitcode=$?

          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
        
          if [ $exitcode -eq 1 ]; then
          echo Terraform Plan Failed!
          exit 1
           else 
          exit 0
           fi
           E
