name: Keyvault migration_mofidy
on:
  workflow_dispatch: 
    inputs:
      source_keyvault:
        type: string
        description: source_keyvault
      destination_keyvault:
        type: string
        description: destination_keyvault
      SECRET_NAMES:
         type: choice
         description: SECRET_NAMES
         default: eky
         options:
          - app
          - camu
env:
    ARM_CLIENT_ID: a5c0e815-b4dd-4453-9d3d-c6d611cfda7e
    clientSecret: Q0J8Q~Dri.BbRPjiUspL6XFQQSr-glUF2C11Rbgv
    ARM_SUBSCRIPTION_ID: d1235549-70af-4c68-ac5a-8f63dc87fdb6
    ARM_TENANT_ID: d30ea4cb-2410-4a99-9194-e7e6a4adcfff
jobs:
  azlogin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: 'Az CLI Login'
        uses: azure/login@v1
        with: 
          creds: "{\"clientId\": \"${{ env.ARM_CLIENT_ID}}\", \"clientSecret\": \"${{ env.clientSecret }}\", \"subscriptionId\": \"${{ env.ARM_SUBSCRIPTION_ID}}\", \"tenantId\": \"${{ env.ARM_TENANT_ID}}\", \"resourceManagerEndpointUrl\": \"https://management.azure.com/\"}"
      
      - name: 'Run basic AZ CLI command'
        run: az account show

      - name: 'Azure PowerShell Action'
        run: |
          SOURCE_KEYVAULT_NAME="${{ github.event.inputs.source_keyvault }}"
          TARGET_KEYVAULT_NAME="${{ github.event.inputs.destination_keyvault }}"
          SECRET_NAMES="${{ github.event.inputs.SECRET_NAMES }}"  # Use the provided SECRET_NAMES
          SECRET_VALUE=$(az keyvault secret show --name $SECRET_NAME --vault-name $SOURCE_KEYVAULT_NAME --query "[?!(contains(name, 'ekyc') || contains(name, 'camunda'))].name" -o tsv)
          az keyvault secret set --name $SECRET_NAME --vault-name $TARGET_KEYVAULT_NAME --value "$SECRET_VALUE"
          done


        
