name: Keyvault migration
on:
  workflow_dispatch: 
    inputs:
      source_keyvault:
        type: string
        description: source_keyvault
        default: plan
      destination_keyvault:
        type: string
        description: destination_keyvault
jobs:
  azlogin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: 'Az CLI Login'
        uses: azure/login@v1
        with: 
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: 'Run basic AZ CLI command'
        run: az account show

      - name: 'Azure PowerShell Action'
        run: |
           
            SOURCE_KEYVAULT_NAME= ${{ github.event.inputs.source_keyvault }}
            TARGET_KEYVAULT_NAME= ${{ github.event.inputs.destination_keyvault }}
            SECRET_NAMES=$(az keyvault secret list --vault-name $SOURCE_KEYVAULT_NAME --query "[].name" -o tsv)
            # Loop over each secret and copy it to the target KeyVault
            for SECRET_NAME in $SECRET_NAMES; do
                echo "Migrating secret: $SECRET_NAME"
                # Get the secret value from the source KeyVault
                SECRET_VALUE=$(az keyvault secret show --name $SECRET_NAME --vault-name $SOURCE_KEYVAULT_NAME --query "value" -o tsv)
                # Set the secret value in the target KeyVault
                az keyvault secret set --name $SECRET_NAME --vault-name $TARGET_KEYVAULT_NAME --value "$SECRET_VALUE"
            done


        
