on:
  workflow_dispatch: 
    inputs:
      source_keyvault:
        type: string
        description: source_keyvault
        default: plan
      destination_keyvault:
        type: choice
        description: destination_keyvault
jobs:
  azlogin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: 'Az CLI Login'
        uses: azure/login@v1
        with: 
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: 'Run basic AZ CLI command'
        run: az account show

      - name: 'Azure PowerShell Action'
        run: |
           az account show
           az keyvault show --name ${{ github.event.inputs.source_keyvault }}


        
