on:
  workflow_dispatch: 
    inputs:
      source_keyvault:
        type: string
        description: Select source action
        default: plan
        # options: 
        #   - apply
        #   - plan
      destination_keyvault:
        type: choice
        description: destination_keyvault
        default: product_rg
        # options: 
        #   - aks-cluster
        #   - aks-externalService-proxies
        #   - ampls
        #   - applications-helm
        #   - ekyc
        #   - esign
        #   - fluxcd
        #   - kubernetes-helm
        #   - monitoring
        #   - ocr
        #   - otds
        #   - postgresql
        #   - product_rg
        #   - smtp-relay
jobs:
  azlogin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: 'Az CLI Login'
        uses: azure/login@v1
        with: 
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: 'Run basic AZ CLI command'
        run: az account show
