on:
  push:
    branches: [ "main" ]
  pull_request:
inputs:
  SourceKV:
  description: 'SourceKV'
  required: true
inputs:
  DestinationKv:
  description: 'DestinationKv'
  required: true
jobs:
  azlogin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: 'Az CLI Login'
        uses: azure/login@v1
        with: 
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: 'Run basic AZ CLI command'
        run: az account show
